language: bash

env:
  global:
  - PATH=$TRAVIS_BUILD_DIR/usr/bin/:$PATH
before_install:
- wget https://github.com/jgm/pandoc/releases/download/1.15.0.5/pandoc-1.15.0.5-1-amd64.deb
  && ar p pandoc-1.15.0.5-1-amd64.deb data.tar.gz | tar zx
- sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra
- sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
- sudo apt-get install texlive-science texlive-humanities
script:
- cd document && make manuscript.tex && make manuscript-biorxiv.pdf
after_success:
- bash push.sh
